### ISSUE TITLE
BeautifulSoup not a dependency

### ISSUE THREAD

**Issue by ilumsden** [llnl/hatchet#40]
In the 2022.1.0 release, running the `install.sh` script produces a `ModuleNotFoundError` for the `bs4` package (BeautifulSoup). The import of this package is in `hatchet/vis/static_fixer.py`.

@slabasan do we want to include BeautifulSoup as a dependency of Hatchet?

**Comment by slabasan** [comment]
We should verify with @cscully-allison about this package when he returns and how we should handle it for the install. I know it was being used to change some static paths in html files to make his interactive visualization work.
